spring.application.name=tradingapp

# DATABASE CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/trading_app
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8081

# JWT
jwt.secret=YOUR_SECRET_KEY